# Site settings
title: SMY Blog
SEOTitle: 孙明月的博客 | SMY_Blog
header-img: img/post-bg-desk.jpg
email: smy_cating@qq.com
description: "卑鄙是卑鄙者的通行证，高尚是高尚者的墓志铭."
keyword: "SMY Blog, 孙明月的博客, sunmingyue, 孙明月, 前端"
url: "http://smy0916.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/smy0916/smy0916.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "卑鄙是卑鄙者的通行证，高尚是高尚者的墓志铭."
sidebar-avatar: /img/avatar_g.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     5016433196
# zhihu_username:     luo-su-meng
github_username:    smy0916
# facebook_username:  
# jianshu_username:   81c007afb604
# twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# plugins: [jekyll-paginate]
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: sunmingyue

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: a3d324a936efbf25bf6d                            #生成的clientID
  clientSecret: 17c0e125d749107d52783b4151b69a73a248f267    #生成的clientSecret
  repo: smy0916/smy0916.github.io    #仓库名称
  owner: smy0916    #github用户名
  admin: smy0916
  distractionFreeMode: false #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname'

# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-143668493-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



